### ISSUE TITLE
-SaveAlpha=1 does not work,lego model not rendered in its "see through" form (e.g. for a transparent color)

### ISSUE THREAD

**Issue by tvhdev** [tcobbs/ldview#10]
It does not "check" the Transparency box, the rendered image is always not transparent.

**Comment by tcobbs** [comment]
I think you are misunderstanding what -SaveAlpha=1 is supposed to do. It makes the background portion of the image transparent (100% transparent, 0 alpha value) in the generated PNG file. I believe what you are looking for is a way to make the default color transparent. This is done by specifying -TransDefaultColor=1 on the command line. I see in LDView's Help.html, that this is improperly documented as being equivalent to the _Trans_ check in the _General->Colors_ box. I will fix Help.html to correctly say _Transparent_ instead of _Trans_.
