### ISSUE TITLE
Unicode character ö not supported in latest codebase

### ISSUE THREAD

**Issue by trevorsandy** [tcobbs/ldview#18]
The latest LDView codebase fails to translate unicode character ö. This behaviour has been present for quite some time. This thread on the LDraw forum illustrates the behaviour: [LPub3D - Submodel not shown in main model](https://forums.ldraw.org/thread-23315-post-31414.html?highlight=lpub3d+submodel#pid31414).

When attempting to render an image at the following path: `"C:\Users\Trevor\Desktop\LPub\JörgSchwarzländer\LPub3D\tmp\001_gearbox_00.ldr"` ...

The latest release build works as expected:
![Screenshot - 06_10_2019 , 23_54_15](https://user-images.githubusercontent.com/13388970/66276907-bb348d80-e897-11e9-8d5c-77d26db98fd0.png)

However, a build from the latest source fails with the following messages:

![Screenshot - 06_10_2019 , 23_56_22](https://user-images.githubusercontent.com/13388970/66276951-08186400-e898-11e9-9f49-9ad11b6601ea.png)

The following shots show the root of the problem. The ConvertUTF16toUTF8 function fails to convert the unicode character in the switch statement beginning at [line 269 in ConvertUTF.c](https://github.com/tcobbs/ldview/blob/3ac19b3743129d12c3ee05df379b65b23708c209/TCFoundation/ConvertUTF.c#L269).

Here the conversion starts with a valid 'src' path
![Screenshot - 06_10_2019 , 23_58_52](https://user-images.githubusercontent.com/13388970/66277053-45c9bc80-e899-11e9-9089-9747622f5a38.png)

Here we see the path conversion is ok up to `J`...
![Screenshot - 07_10_2019 , 00_11_55](https://user-images.githubusercontent.com/13388970/66277032-04391180-e899-11e9-8c02-6421a060bb17.png)

At the `ö` character, garbage is returned.
![Screenshot - 07_10_2019 , 00_12_32](https://user-images.githubusercontent.com/13388970/66277019-e1a6f880-e898-11e9-86b4-24051970ba9f.png)

The conversion completes with the following return:
![Screenshot - 06_10_2019 , 23_59_25](https://user-images.githubusercontent.com/13388970/66277063-67c33f00-e899-11e9-962f-d24bcf567e87.png)

Cheers,

**Comment by trevorsandy** [comment]
This behaviour is corrected with the following updates to [mystring.cpp](https://github.com/tcobbs/ldview/blob/3ac19b3743129d12c3ee05df379b65b23708c209/TCFoundation/mystring.cpp):

![Screenshot - 07_10_2019 , 22_27_46](https://user-images.githubusercontent.com/13388970/66346142-cc41d500-e951-11e9-9293-035458904186.png)

at `bool utf8towstring(std::wstring& dst, const char *src, int length /*= -1*/)`
add at line 2067:
```
	//*** Skip unicode conversion
	stringtowstring(dst, src);
	return true;
```

at `bool ucstringtoutf8(std::string& dst, CUCSTR src, int length /*= -1*/)`
replace at line 2219:
```
	//*** return wstringtoutf8(dst, src, length);
	wstringtostring(dst, src);
	return true;
```

at `TCExport bool ucstringtoutf8(std::string& dst, const ucstring& src)`
replace at line 2231:
```
	//*** return wstringtoutf8(dst, src);
	wstringtostring(dst, src);
	return true;
```

at `UCSTR utf8toucstring(const char *src, int length /*= -1*/)`
add at line 2275:
```
	//*** Skip unicode conversion
	std::wstring _dst;
	stringtowstring(_dst, src);
	return (UCSTR)_dst.c_str();
```

Cheers,

**Comment by tcobbs** [comment]
Thanks. I need to investigate the ramifications of using mbsrtowcs instead
of the (apparently broken) ConvertUTF functions. ConvertUTF came directly
from Unicode, Inc., but it is very old, and hasn't been supported in a long
time. I have to assume that since this change worked for you, it means that
LDView always sets the C locale to UTF-8. However, I need to verify that
for sure, since the mbsrtowcs function only works correctly if the input is
in the same multi-byte-string format as what is specified by the C locale.

--Travis

**Comment by trevorsandy** [comment]
Trials on Windows (x86 and x86_64 builds) seem to work; however on Unix, my build abends with 
```
*** Error in `./ldview': munmap_chunk(): invalid pointer: 0x0000000001ac4de8 ***
Aborted (core dumped)
```
Cheers,

**Comment by tcobbs** [comment]
Looking further, your change works in this case, but isn't correct. There
are two possible sources of the bug:

   1. The UTF8 conversion code is broken.
   2. (More likely) The Windows LDView code isn't converting the original
   filename to UTF8, and is instead using the current locale.

The change in the LDView source (that broke things) was to properly treat
all LDraw filenames as UTF8, since the LDraw file format requires this.
However, if the Windows code doesn't correctly convert input filenames from
the UI into UTF8, this problem will happen.

--Travis

**Comment by tcobbs** [comment]
As an aside, I think using mbsrtowcs (which is what your change effectively
causes to happen) is probably the right solution, but only after using
setlocale(C_TYPE, NULL) to read the currently local, then setlocale(C_TYPE,
"en_US.utf8") to set the locale to UTF8, then setting it back to whatever
it was before afterwards. This will only work if the input is valid UTF8.

--Travis

**Comment by trevorsandy** [comment]
Indeed, your second source is where I started. I concluded, probably wrongly, that the ConvertUTF16toUTF8 routine was responsible for setting the original filename to UTF8.

**Comment by tcobbs** [comment]
It turns out also that Windows doesn't support the UTF-8 locale. However,
it does have functions to convert back and forth, so I will probably go
with the UTF-8 locale code for non-Windows, and Windows-specific code for
Windows. I'll have to check that the locale code does in fact work in Linux
and on the Mac, though. It might take a few days.

--Travis

**Comment by trevorsandy** [comment]
Hmmm, I thought UTF8 was supported since VS2015 ?

![Screenshot - 08_10_2019 , 08_28_28](https://user-images.githubusercontent.com/13388970/66372339-09d04d80-e9a6-11e9-91e9-818819ec92d3.png)

Cheers,

**Comment by tcobbs** [comment]
That may be so, but I think I'm using VS 2013. In any event, I committed
changes that hopefully fixes things (using Windows API in Windows). Go
ahead and pull and give them a try. The fixes are currently Windows-only,
but both the Mac version and the Linux version have native UTF-8 filenames,
so I think this particular problem doesn't exist in Linux or on the Mac.

Note that I don't think the problem was universal. I think you could open
the file from the LDView UI, it just didn't work when specified on the
command line. After the fix, arbitrary Unicode filenames should work in all
locations (command line, ldr file specified from another ldr file, ldr file
inside an mpd).

--Travis

**Comment by tcobbs** [comment]
The documentation claims setlocale will fail with a UTF-8 code page, even
in VS 2019:

https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/setlocale-wsetlocale?view=vs-2019

Not sure if the documentation is wrong or not, but since I worked around
the problem, I'm not going to investigate further.

--Travis

**Comment by trevorsandy** [comment]
Excellent! Many thanks. I'll give it a go. 

On another topic, I tried my hand at enabling stud logos in my instance of LDView. The ticket is https://github.com/trevorsandy/lpub3d/issues/347 - the commit is captured at the bottom. I'm not sure I did the right thing regarding high and low level of detail.  Also, I did not include the UI layer to set the logo preference (0 - 5).

Cheers,

**Comment by trevorsandy** [comment]
Correction: The LDView change for stud logo is here: https://github.com/trevorsandy/ldview/commit/c441427939ca0a718255e669d9d8309911450e56 

Cheers,

**Comment by tcobbs** [comment]
I'll have to think about that one. For full support there needs to be an
option in settings. And the stud-logo* and stud2-logo* files aren't
official yet, which could confuse things.

--Travis

**Comment by trevorsandy** [comment]
The core elements for the UI are there. I use them in my custom Qt-based LDV library used to interface with LDView. Below you can see the LDV preferences dialogue.

![Screenshot - 08_10_2019 , 08_59_18](https://user-images.githubusercontent.com/13388970/66373935-266e8480-e9aa-11e9-9ba4-cde0ca09549c.png)

My thinking was LDView fully supports unofficial files/parts so adding this option does not break new ground.

What's still to be done on the LDView side is to add the preferences  UI for the other platforms - Windows, macOS and the Qt.

Cheers,

**Comment by trevorsandy** [comment]
My trials were not successful.

On my system, `WideCharToMultiByte` fails at conversion just as `ConvertUTF16toUTF8` did, so the unexpected behaviour is unchanged.

![Screenshot - 08_10_2019 , 13_02_13](https://user-images.githubusercontent.com/13388970/66391447-6e52d300-e9cd-11e9-9945-e29c066c2a56.png)

![Screenshot - 08_10_2019 , 11_08_41](https://user-images.githubusercontent.com/13388970/66385985-bcfa7000-e9c1-11e9-98f3-1c26bcbdd8f6.png)

Interestingly however, if I roll back all your workaround updates and set the locale to UTF8 using the following code in `LDViewMain.cpp`...

![Screenshot - 08_10_2019 , 11_58_26](https://user-images.githubusercontent.com/13388970/66387100-8cb3d100-e9c3-11e9-8d7d-df42ec560664.png)

`ConvertUTF8toUTF16` works - even with a path that appears (at least in the IDE Locals window) malformed by the previous conversion from `ConvertUTF16toUTF8` .

![Screenshot - 08_10_2019 , 11_55_25](https://user-images.githubusercontent.com/13388970/66386434-8a04ac00-e9c2-11e9-99a7-4876be72c3e4.png)

So it looks like with only the few lines of code that set the locale to UTF8, the behaviour is as expected.

![Screenshot - 08_10_2019 , 13_15_46](https://user-images.githubusercontent.com/13388970/66391652-f5a04680-e9cd-11e9-9d86-772f49e96a3e.png)

I think the problem is unique to Windows and it's patchy UTF codepage support. When the locale is properly set to UTF8, the ConvertUTF functions appear to be working so the previous code seems to have been ok with the exception of not setting the locale.

FYI, the MS documentation reference you posted is out of date. See the latest update here: [setlocale and UTF-8 codepage #1469](https://github.com/MicrosoftDocs/cpp-docs/issues/1469)

Cheers,

**Comment by tcobbs** [comment]
OK, I'm a little confused. First you say that it fails in converting from
wide characters to UTF-8, and then later state that after making changes it
successfully converts from UTF-8 to wide characters.  I can't think of any
way for WideCharToMultiByte to fail when trying to convert to UTF-8. I can
think of plenty of ways that MultiByteToWideChar would fail when converting
from UTF-8.

Note that the IDE shows char strings using the OS's current code page. So a
UTF-8 string is normally expected to display incorrectly there*. Also note
that I did in fact test with setlocale and UTF8, and it didn't work. I'm
pretty sure LDView still uses VC++ 2013, and I am loath to change that
right now.

Please send me a zip of your LPub output directory that includes the
problem sub-directory. Also, while I tested an LDraw file that references
other LDraw files with ö in their filename, I don't think I tested an LDraw
file in a directory with ö in its name that references other files (which
is what you have).

* I found a post that indicated that a while back Microsoft was adding
support for UTF-8 as a code page in Windows. However, it was only a Beta
feature at the time, and the interface has completely changed since then. I
can't find any reference to a code page setting anywhere at all (either in
the old Control Panel or the new POS Settings app).

--Travis

**Comment by trevorsandy** [comment]
> OK, I'm a little confused. First you say that it fails in converting from
wide characters to UTF-8, and then later state that after making changes it
successfully converts from UTF-8 to wide characters.  I can't think of any
way for WideCharToMultiByte to fail when trying to convert to UTF-8. I can
think of plenty of ways that MultiByteToWideChar would fail when converting
from UTF-8.

I too was a bit perplexed about the result so I downloaded and built the latest code three times for both x86 and x86_64. Each time, the result was the same as shown in the shots. 

> Note that the IDE shows char strings using the OS's current code page. So a UTF-8 string is normally expected to display incorrectly there*.

Yep, this was my understanding as well.

[JörgSchwarzländer.zip](https://github.com/tcobbs/ldview/files/3703615/JorgSchwarzlander.zip)

Cheers,

**Comment by tcobbs** [comment]
The problem is that LDrawIni (which was written by Lars Hassing) doesn't
work when the model's path includes special characters in UTF-8. That makes
it so that LDView doesn't try to open any files in the current model's
directory. I'll fix it.

--Travis

**Comment by tcobbs** [comment]
Hopefully this fixes it:

https://github.com/tcobbs/ldview/commit/276169af2d506a1ec0148575553c05a08fc221ce

--Travis

**Comment by trevorsandy** [comment]
Excellent! It’s good to see you found the source of the behaviour. Considering the official release uses LDrawini and also somehow works with multibyte special characters made this source quite elusive.

Cheers,

**Comment by tcobbs** [comment]
Before I updated everything to use UTF-8 for the non-wide characters, it
would work as long as your current character set contained the special
character in the filename. For most people running Windows, their language
settings would ensure that their character set contained the used
characters in their own language. I'm pretty sure if you tried before with
a Japanese directory name, it would have failed (even if Windows was
configured for Japanese). Japanese directory and file names should now work
on all systems (fingers crossed).

--Travis

**Comment by trevorsandy** [comment]
Success! 

Many thanks for taking the time to treat this item. 

Cheers,

**Comment by trevorsandy** [comment]
Just a little post mortem note. 

For maintainability purposes, perhaps it's better to update your [comments](https://github.com/tcobbs/ldview/blob/9f289f9b79c4d19bbfd25fa3c10ae7183c830dae/TCFoundation/mystring.cpp#L6) suggesting "ConvertUTF has issues". That the root cause of this ticket was LDrawini's inability to process UTF-8 special characters, maybe it's better to add substitute the previous comments with this new information. 

The major part of the updates that treat this ticket circumvent the ConvertUTF routines and instead use UTF-8 CTYPE locale on non-Windows installs and Windows-specific routines utilizing WideCharToMultiByte conversion on Windows. As the ConvertUTF routines are now known to not implicate the unexpected behaviour, these updates simply take an alternate approach to further enabling comprehensive UTF-8 support as specified by the LDraw file format.

Do not hesitate to update these remarks if anything is missing or not accurate.

Cheers,

**Comment by tcobbs** [comment]
I modified the comment a bit, but the fact is that I did find various
places claiming that ConvertUTF had bugs, so I figure having that
documented in the code is a good thing.

https://github.com/tcobbs/ldview/commit/5d7ea6327132913dff0039724970c78ca9345506

--Travis
