### ISSUE TITLE
Odd texmap rendering issue with part 004589a.dat

### ISSUE THREAD

**Issue by alex-taylor** [tcobbs/ldview#24]
![Image1](https://user-images.githubusercontent.com/5150717/84590470-e6ac4680-ae2e-11ea-89fe-93276f1c079c.png)

Not clear why this is happening!  If you open the part itself then it renders correctly, the problem only appears when it's used in a model.

**Comment by tcobbs** [comment]
I tracked down the problem to my textures not working right on colored geometry. (By that, I mean geometry that doesn't use color 16.) I have fixed the problem in the development code.

I added a no-vote the part with an acknowledgement that LDView doesn't render it correctly, but that this is due to an LDView bug. I also added a separate no-vote indicating that it is my belief that you should put your current geometry in a TEXMAP FALLBACK section, and have a single red quad (using 0 !: to make it TEXMAP-only) as the only non-fallback geometry.
