### ISSUE TITLE
Texmap z-fighting issue at high magnification

### ISSUE THREAD

**Issue by alex-taylor** [tcobbs/ldview#25]
![Image1](https://user-images.githubusercontent.com/5150717/84641428-e4abbb80-aef2-11ea-834b-7887a4e2a562.png)

Only happens when the part is used in a model - viewing the part itself is fine.

The issue is not present in the 4.3 release, just in the build I've done from current github code.

**Comment by tcobbs** [comment]
@alex-taylor Some questions:
1. What is your FOV set to?
2. Do you have "Draw transparent textures last" checked on the Primitives tab of Preferences? (Note: That check box is going to be removed, and LDView in the future is going to always behave as it does now when it is checked. Unchecking it causes problems.)
3. About where is the "Offset" slider set right below "Draw transparent textures last"?
4. Does the problem go away if that slider is moved all the way to the right?
5. Can you send me a sample model at the ldview email address?

**Comment by alex-taylor** [comment]
1. 30
2. Yes
3. All the way to the left
4. Yes, that fixes the issue.
5. Attached... :-)

I don't know if this is relevant, but I'm running on a hdpi screen, which of course isn't supported in 4.3.

[590 - Engine Co. No. 9.zip](https://github.com/tcobbs/ldview/files/4785492/590.-.Engine.Co.No.9.zip)

**Comment by alex-taylor** [comment]
After some more testing, I've found that texmaps bleed though even with the slider all the way to the left: 

[sample.zip](https://github.com/tcobbs/ldview/files/4785799/sample.zip)

If you rotate the view so that you're looking at the underside of the part and then zoom out as far as you can go, you will see the pattern appear on the inside of the cone.

**Comment by tcobbs** [comment]
Unfortunately, all of the things you see are limitations of LDView, and not likely to ever change. It draws the textures after the underlying geometry, and in order to do that, it has to push the underlying geometry away from the camera. Furthermore, when edge lines are enabled, all polygons are pushed away from the camera so that the edge line will be visible. The Offset slider controls how far it pushes the geometry to make space for textures. Furthermore, the amount of push is different based on whether or not edge lines are enabled, and whether or not there is any transparent geometry. To top it all off, the behavior the user sees is conditional upon their graphics card. Some give more precision to the depth buffer, which lessens these problems.
