### ISSUE TITLE
Model stats

### ISSUE THREAD

**Issue by mjhorvath** [tcobbs/ldview#49]
Could you maybe add a popup dialog listing the number of quads, tris, vertices, parts, sub-models, lines of different types, etc. etc.? Thanks!

**Comment by tcobbs** [comment]
@mjhorvath Please contact the LDView email address, and I'll send you a link to a test build. If you don't want the test build to be Win64, let me know what you want instead.

I didn't include a vertex count. Triangles*3 + Quads*4 + Lines*2 + Edge Lines*2 + Conditional Lines*2 would be easy to implement, but doing so would be misleading. (Some vertices get shared during rendering, but I don't have access to an accurate count.) My statistics include parts, models, triangles, quads, (non-edge) lines (almost always 0), edge lines, and conditional lines. I also count comment lines, empty lines and unknown lines, but didn't feel that displaying statistics for those would be useful. (As an aside, due to part headers, the comment line count in car.ldr is 31,838, while the highest other count in car.ldr is edge lines, of which there are 15,567.)

**Comment by tcobbs** [comment]
@mjhorvath one last chance to respond to test this before I close this issue.
