### ISSUE TITLE
Errors & Warnings copy-to-clipboard does not copy to the clipboard

### ISSUE THREAD

**Issue by trevorsandy** [tcobbs/ldview#70]
**Describe the bug**
Clicking the Errors & Warnings copy-to-clipboard button does not copy anything to the clipboard as pasting (or ctrl+v) does not paste the contents from the Errors & Warnings dialog.

**To Reproduce**
Steps to reproduce the behavior (On Windows):
1. Open a file with known errors and or warnings
2. The Errors & Warnings dialog should automatically present but if it does not, select Tools->Errors & Warnings... (Ctrl+Shift+E) from menu actions.
3. Click 'Copy Error to Clipboard'
4. Open Notepad or any other text editor and enter (ctrl+v) or 'paste' if this menu action is enabled.
5. The contents of the Errors & Warnings dialog are not pasted as expected.

**Expected behavior**
The contents of the Errors & Warnings dialog should be pasted into the text editor

**Screenshots**
![LDView_About](https://user-images.githubusercontent.com/13388970/229655749-89a9dc1b-4502-4e3e-95b8-b4a16c5f8edb.png)

![LDView_Errors_Copy_To_Clipboard](https://user-images.githubusercontent.com/13388970/229655777-9f293b7f-68f9-49f7-84d9-6d9027edc6ce.png)

**Platform:**
 - OS: Windows
 - Version 11
 - CPU Architecture X86-64

**Additional context**
Using latest version of LDView from GitHub releases

Cheers,

**Comment by tcobbs** [comment]
@trevorsandy I cannot reproduce the problem when following your exact steps. _However_, I believe that you are in a state where no item in the list is selected. While it is impossible to deselect once there is a selection, other actions can make it so that no item is selected. I believe that you are in such a state.

I pushed a commit to disable the "Copy Error to Clipboard" button when no item is selected:

https://github.com/tcobbs/ldview/commit/4f75ac952a402168486137adee276a10095e6a7c

The above change also makes it so that the selection is shown even when the focus is on another control (which happens when you push the button). Before I changed it to do this, there was no way to know what was selected when the tree view wasn't focused. (Consequently, I can't tell by your screenshot if there is a selection or not.) I'm hoping that your tree view did not have a selected item, and that was the source of the problem. Please let me know if things work after applying the above commit.

**Comment by trevorsandy** [comment]
Thank you for the update and improvement.

Indeed, I'm also not able to reproduce the reported behaviour. 

Cheers,
