### ISSUE TITLE
use ldraw zip archive as alternative to ldraw directory

### ISSUE THREAD

**Issue by nathaneltitane** [tcobbs/ldview#80]
**Is your feature request related to a problem? Please describe.**
Allow the user to select a directory containing a zip archive of the ldraw parts library as option.

**Describe the solution you'd like**
Use zip archive of ldraw library instead of an unpacked folder - detect ldrawunf.zip as well (see leocad code for details - screenshot from leocad)

![image](https://github.com/tcobbs/ldview/assets/5674757/37cccb80-d598-420d-ab37-1bd63fea9f95)

**Describe alternatives you've considered**
n/a

**Comment by tcobbs** [comment]
I'm working on this feature now. It is actually something that I have considered for a while now, but have finally started working now that it has been officially requested by a user.

Having said that, while I'm going to allow you to use a zip file as the main LDraw library, it won't be allowed to completely replace the LDraw directory due to the fact that Unofficial part downloading needs an LDraw directory to download into. However, if the user _does_ select an LDraw Zip (new setting), then the LDraw Directory that the user chooses won't be required to have `parts` and `p` subdirectories.

I'm also not sure how to deal with possible support for an unofficial parts zip.

**Comment by nathaneltitane** [comment]
> I'm working on this feature now. It is actually something that I have considered for a while now, but have finally started working now that it has been officially requested by a user.
> 
> Having said that, while I'm going to allow you to use a zip file as the main LDraw library, it won't be allowed to completely replace the LDraw directory due to the fact that Unofficial part downloading needs an LDraw directory to download into. However, if the user _does_ select an LDraw Zip (new setting), then the LDraw Directory that the user chooses won't be required to have `parts` and `p` subdirectories.
> 
> I'm also not sure how to deal with possible support for an unofficial parts zip.

Amazing!

Well my request takes from the fact that LeoCAD has had the feature present for some time now.
Leo's a pproach to unofficial files  is relatively straightforward: 

when using the zip for the official/main library, it will automatically scan for the unofficial zip in the same directory.

I would assume that the library is populatedby a combination of zip archives and or directory/ies if the one or the other is not found:
official zip, no unofficial zip >>> then unofficial directory
no officiall zip, then official directory, unofficial directory

@leozide may be able to help

**Comment by pbartfai** [comment]
@tcobbs can we close this issue?

**Comment by tcobbs** [comment]
Not yet in a release, but this is now implemented.
